version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_application
    command: tail -f /dev/null
    working_dir: /usr/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    container_name: project_name_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
