version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: "boiler_place"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boiler_place
    ports:
      - "5432:5432"